<?php
$dbtype="mysql";
$dbserver = 'localhost';
$dbslcl = 'MYSQL_DATABASE_IP_ADDRESS';
$dbspub = 'MYSQL_DATABASE_PUBLIC_IP';
$dbun = 'MYSQL_DATABASE_USERNAME';
$dbpw = 'MYSQL_DATABASE_PASSWORD';
$dbname = 'MYSQL_DATABASE_NAME';
$defpage="1";
$groupval="1";
$uselogins="0";
$appname="";
$sparkaccesstoken="BOT_SPARK_ACCESS_TOKEN";
$botemail="BOT_EMAIL_ADDRESS";
$webhook="FULL_WEBHOOK_URL";

$personid = "BOT_PERSON_ID";    // This can be retrieved automatically via API, I just never added to the code to make that work
$personemail = $botemail;
?>
